env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
  - plugin:@typescript-eslint/strict
  - plugin:@typescript-eslint/strict-type-checked

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  project: true
  sourceType: module

plugins:
  - '@typescript-eslint'

rules: {}
